version: "3.7"

services:
 cms:
  image: min-madplan/strapi
  build:
   context: ./cms
   dockerfile: Dev.Dockerfile
  command: sh -c "chokidar_usepolling=1 strapi develop"
  ports:
   - 1337:1337
  volumes:
   - ./cms:/cms
   - /cms/node_modules
     
 gatsby:
  image: min-madplan/gatsby-app
  build:
   context: ./app
   dockerfile: Dev.Dockerfile
  command: sh -c "chokidar_usepolling=1 gatsby develop --host=0.0.0.0"
  ports:
   - 8000:8000
  volumes:
   - ./app:/app
   - /app/node_modules
  environment:
   - STRAPI_URL=http://cms:1337
  links:
   - cms
  
  
  
  
  
  
  
#  docker run -it -p 1337:1337 -v ${pwd}/cms:/srv/app strapi/strapi
  
#  docker run -ti --rm -p 8000:8000 -v ${PWD}/app:/app vormadal/gatsby-cli sh -c "cd app && gatsby develop --host=0.0.0.0"